# Generated by Django 2.2.3 on 2019-07-13 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('email2', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('friends', models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='api.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('C', 'Cancelled'), ('D', 'Done')], max_length=1)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Profile')),
                ('payor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Profile')),
            ],
        ),
    ]
