# Generated by Django 2.2.3 on 2019-07-13 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
