# Generated by Django 2.2.2 on 2019-06-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loans',
            field=models.ManyToManyField(to='api.Loan'),
        ),
    ]
