# Generated by Django 2.2.2 on 2019-06-21 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190620_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.User'),
        ),
    ]
