# Generated by Django 2.2.2 on 2019-06-21 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190620_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loans',
        ),
    ]
