# Generated by Django 2.2.2 on 2019-06-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190620_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='admin', max_length=60),
            preserve_default=False,
        ),
    ]
