# Generated by Django 2.2.2 on 2019-06-21 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='api.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='loans',
            field=models.ManyToManyField(blank=True, to='api.Loan'),
        ),
    ]
