# Generated by Django 2.1.5 on 2019-02-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False),
        ),
    ]
